id: IDE444709
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:55:26+00:00'
last_modified: '2022-06-09T08:42:23.556478+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD107142
  title: གསུང་འབུམ། ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    00B7:
      image_group_id: I1PD107144
      title: Volume 1 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 582
      order: 1
      base_file: 00B7.txt
    8A50:
      image_group_id: I1PD107145
      title: Volume 2 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 580
      order: 2
      base_file: 8A50.txt
    E5D7:
      image_group_id: I1PD107146
      title: Volume 3 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 382
      order: 3
      base_file: E5D7.txt
    90EE:
      image_group_id: I1PD107147
      title: Volume 4 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 562
      order: 4
      base_file: 90EE.txt
    ADD9:
      image_group_id: I1PD107148
      title: Volume 5 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 630
      order: 5
      base_file: ADD9.txt
    88A2:
      image_group_id: I1PD107149
      title: Volume 6 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 494
      order: 6
      base_file: 88A2.txt
    7FD1:
      image_group_id: I1PD107150
      title: Volume 7 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 612
      order: 7
      base_file: 7FD1.txt
    '4536':
      image_group_id: I1PD107151
      title: Volume 8 of gsung 'bum/_o rgyan 'jigs med chos kyi dbang po
      total_pages: 576
      order: 8
      base_file: 4536.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
